name: Fetch recent blog posts 2
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  fetch-recent-blog-posts:
    name: Fetch recent blog posts 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Run node script
        run: npm run build
